---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: latest

platforms:
- name: ubuntu-12.10
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
suites:
- name: server
  run_list:
    - recipe[openldap::server]
    - recipe[openldap::auth]
    - recipe[minitest-handler]
  attributes:
    openldap:
      rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
      basedn: "dc=example, dc=com"
      server: "ldap.example.com"
      preseed_dir: "/tmp/does_not_exist"
- name: unmanaged_ssl
  run_list:
    - recipe[openldap-test::ssl]
    - recipe[openldap::server]
    - recipe[openldap::auth]
    - recipe[minitest-handler]
  attributes:
    openldap:
      rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
      basedn: "dc=example, dc=com"
      server: "ldap.example.com"
      manage_ssl: false
      tls_checkpeer: true
      pam_password: sha
      ssl_dir: "/etc/ldap/ssl"
      ssl_cert: "/etc/ldap/ssl/ldap.example.com.pem"
      ssl_key: "/etc/ldap/ssl/ldap.example.com.pem"
      cafile: "/etc/ldap/ssl/ldap.example.com.pem"
- name: tls_disabled
  run_list:
  - recipe[openldap::server]
  - recipe[openldap::auth]
  - recipe[minitest-handler]
  attributes:
   openldap:
     server: localhost
     rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
     tls_enabled: false
     passwd_ou: peeps
     shadow_ou: ninjas
     group_ou: pirates
     automount_ou: barge
